     # Run Wiz CLI IaC scan
      - name: Run wiz-cli IaC scan
        run: |
          ./wizcli iac scan --path ${{ env.SCAN_PATH }} \
                           --policy "$IAC_POLICY" \
                           --output wiz-iac-scan-results.json,sarif,true \
                           --policy-hits-only

      # Upload SARIF results to GitHub
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: wiz-iac-scan-results.json
        continue-on-error: true
        if: always()
